language: php

php:
  - 7.2
  - 7.3
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm
  fast_finish: true